server:
  port: 8082

spring:
  application:
    name: consumer-service #应用/微服务名字
  cloud:
    nacos:
      discovery:
        username: nacos
        password: nacos
        server-addr: localhost:8848
        namespace: public

logging:
  level:
    root: debug

