server:
  port: 7000 #a:7000/b:8000/c:9000
spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        username: nacos
        password: nacos
  application:
    name: a-service #a-service/b-service/c-service

  sleuth:
    #采样器
    sampler:
      #采样率，采样率是采集Trace的比率，默认0.1
      probability: 1.0
      #每秒数据采集量，最多n条/秒Trace
      rate: 10000
  zipkin:
    #设置zipkin服务端地址
    base-url: http://localhost:9411



logging:
  level:
    root: debug #为演示需要，开启debug级别日志


