server:
  port: 8084

spring:
  application:
    name: provider-service #应用/微服务名字
  cloud:
    nacos:
      discovery:
        username: nacos
        password: nacos
        server-addr: localhost:8848
        namespace: public

