server:
  port: 8089

spring:
  application:
    name: warehouse-service
  cloud:
    nacos:
      discovery:
        username: nacos
        password: nacos
        server-addr: localhost:8848
        namespace: public