server:
  port: 8080

spring:
  application:
    name: nacos-test
  cloud:
    nacos:
      discovery:
        username: nacos
        password: nacos
        server-addr: localhost:8848
        namespace: public