
server:
  port: 8090


spring:
  application:
    name: sentinel-sample #\u5E94\u7528\u540D&\u5FAE\u670D\u52A1id
  cloud:
    sentinel:
      #Sentinel Dashboard\u901A\u4FE1\u5730\u5740
      transport:
        dashboard: localhost:9100
      #\u53D6\u6D88\u63A7\u5236\u53F0\u61D2\u52A0\u8F7D
      eager: true
    nacos:
      #Nacos\u6CE8\u518C
      discovery:
        server-addr: localhost:8848
        username: nacos
        password: nacos



management:
  endpoints:
    #\u5C06\u6240\u6709\u53EF\u7528\u7684\u76D1\u63A7\u6307\u6807\u9879\u5BF9\u5916\u66B4\u9732
    web:
      exposure: #\u53EF\u4EE5\u8BBF\u95EE /actuator/sentinel\u8FDB\u884C\u67E5\u770BSentinel\u76D1\u63A7\u9879
        include: '*'

